# use datapasta to paste vector (vertical) from past grants
# update last paste date here: 7-apr-2021
# 
past <- c("Grant#\tTitle\tSponsor Name\tRole in Grant\tTotal Direct/Indirect\tBegin Dt\tEnd Dt",
          "Agreement\tImproving the Quality and Cost of Care among High Risk Inflammatory Bowel Disease Patients",
          "[Updt By: phiggins]",
          "Twine Clinical Consulting, LLC\tPI\t$185,002\t08/18\t12/19\tEdit\tDelete",
          "Evaluation of APG-1244 as a gut-targeted anti-fibrotic compound:Testing in vitro, and in vivo in Mouse and Rat Models",
          "[Updt By: phiggins]",
          "Ascentage Pharma Group Corpora\tPI\t$604,965\t06/18\t11/19\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Upadacitinib (ABT-494) in Subjects with Moderately to Severely Active Crohn's Disease Who Have Inadequately Responded to or are Intolerant to Biologic Therapy",
          "[Updt By: phiggins]",
          "AbbVie, Inc.\tPI\t$1,442,642\t01/18\t11/20\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Upadacitinib (ABT-494) in Subjects with Moderately to Severely Active Crohn's Disease Who Have Inadequately Responded to or are Intolerant to Conventional Therapies but Have Not Failed Biologic Therapy",
          "[Updt By: phiggins]",
          "AbbVie, Inc.\tPI\t$1,446,565\t01/18\t11/20\tEdit\tDelete",
          "A Survey of Inflammatory Bowel Disease Patients on Health Insurance Satisfaction",
          "[Updt By: phiggins]",
          "Takeda Pharmaceutical Company\tPI\t$31,862\t12/17\t12/19\tEdit\tDelete",
          "Sponsored Clinical Trial Agreement for Protocol SHP647-302\tA Phase 3 Randomized, Double-blind, Placebo-controlled, Parallel group Efficacy and Safety Study of SHP647 as Induction Therapy in Subjects with Moderate to Severe Ulcerative Colitis (FIGARO UC 302)",
          "[Updt By: phiggins]",
          "Shire Human Genetic Therapies\tPI\t$108,340\t11/17\t11/19\tEdit\tDelete",
          "Sponsored Clinical Trial Agreement for Protocol SHP647-303\tA Phase 3 Randomized, Double-blind, Placebo-controlled, Parallel-group Efficacy and Safety Study of SHP647 as Maintenance Therapy in Subjects With Moderate to Severe Ulcerative Colitis (FIGARO UC 303)",
          "[Updt By: phiggins]",
          "Shire Human Genetic Therapies\tPI\t$129,352\t11/17\t11/20\tEdit\tDelete",
          "ECOSPOR IV: AN OPEN-LABEL EXTENSION OF STUDY SERES-012 EVALUATING SER-109 IN ADULT SUBJECTS WITH RECURRENT CLOSTRIDIUM DIFFICILE INFECTION (RCDI)",
          "[Updt By: phiggins]",
          "Seres Therapeutics\tPI\t$108,751\t10/17\t10/20\tEdit\tDelete",
          "ECOSPOR III: A Phase 2 Multicenter, Randomized, Double-Blind, Placebo-Controlled, Parallel-Group Study to Evaluate the Safety, Tolerability, and Efficacy of SER-109 vs. Placebo to Reduce Recurrence of Clostridium difficile Infection (CDI) in Adults Who Have Received Antibacterial Drug Treatment for Recurrent CDI (RCDI).",
          "[Updt By: phiggins]",
          "Seres Therapeutics\tPI\t$98,525\t10/17\t09/19\tEdit\tDelete",
          "Statement of Work for Protocol M16-006 under Master Clinical Study Agreement\tA Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Risankizumab in Subjects with Moderately to Severely Active Crohn's Disease",
          "[Updt By: phiggins]",
          "AbbVie, Inc.\tPI\t$1,195,261\t09/17\t09/19\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Study to Evaluate the Safety and Efficacy of ABT-494 for Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: phiggins]",
          "AbbVie, Inc.\tPI\t$277,088\t02/17\t01/20\tEdit\tDelete",
          "Statement of Work for M14-234 under Master Agreement\tA Multicenter, Randomized, Double-Blind, Placebo-Controlled Study to Evaluate the Safety and Efficacy of ABT-494 for Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: phiggins]",
          "AbbVie, Inc.\tPI\t$464,573\t02/17\t01/20\tEdit\tDelete",
          "Dysbiosis-induced luminal mal metabolism in ulcerative colitis increases the risk for Clostridium difficile infection",
          "[Updt By: phiggins]",
          "Crohn's and Colitis Foundation\tCo-I with Effort\t$347,490\t01/17\t12/19\tEdit\tDelete",
          "Study of a Prospective Adult Research Cohort with Inflammatory Bowel Disease (SPARC IBD)",
          "[Updt By: phiggins]",
          "Crohn's and Colitis Foundation\tPI\t$471,950\t12/16\t12/19\tEdit\tDelete",
          "A Phase 2, Multicenter, Randomized, Double-Blind, Parallel, Placebo-Controlled Study of LY3074828 in Subjects with Moderate to Severe Ulcerative Colitis",
          "[Updt By: phiggins]",
          "Lilly USA, LLC\tPI\t$33,188\t07/16\t06/20\tEdit\tDelete",
          "A Phase 2, Multicenter, Randomized, Double-Blind, Parallel, Placebo-Controlled Study of LY3074828 in Subjects with Moderate to Severe Ulcerative Colitis",
          "[Updt By: phiggins]",
          "Eli Lilly and Company\tPI\t$222,615\t07/16\t06/20\tEdit\tDelete",
          "Amendment#1\tA Multi-Center, Open-Label, Study of CP-690,550 In Subjects With Moderate To Severe Ulcerative Colitis",
          "[Updt By: phiggins]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, Inc.\tPI\t$111,419\t06/16\t06/20\tEdit\tDelete",
          "5 R01 DK109032-04\tNonlinear Ultrasound: an Imaging Biomarker of Intestinal Fibrosis in Crohn's Disease",
          "[Updt By: phiggins]",
          "NIH-DHHS-US\tPI\t$2,381,264\t04/16\t03/20\tEdit\tDelete",
          "A Phase 3, Randomized, Double-blind, Placebo-controlled, Parallel-group, Multicenter Protocol to Evaluate the Safety and Efficacy of Ustekinumab Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: phiggins]",
          "Janssen Research and Developme through a consortium with Parexel International, LLC\tPI\t$542,904\t03/16\t02/20\tEdit\tDelete",
          "5 K23 DK101687-05\tImproving Prediction of Medical Responsiveness and Clinical Outcomes in Crohn's Disease",
          "[Updt By: phiggins]",
          "NIH-DHHS-US\tCo-I without Effort\t$903,236\t08/15\t06/20\tEdit\tDelete",
          "Agreement for Conduct of Non-Interventional Study-Protocol C87075\tA Non-Interventional Long-term Post-Marketing Registry of Patients Treated with Certolizumab Pegol (Cimzia®) for Crohn's Disease",
          "[Updt By: phiggins]",
          "UCB Biosciences, Inc., through a consortium with PRA Health Sciences\tPI\t$1,395\t10/10\t02/20\tEdit\tDelete",
          "Agreement for Conduct of Non-Interventional Study-Protocol C87075\tCimzia study amendment #2",
          "[Updt By: phiggins]",
          "UCB through a consortium with Schwarz Biosciences\tPI\t$8,000\t10/10\t02/20\tEdit\tDelete",
          "Agreement For Conduct of Non-Interventional Study-Protocol C87075\tA Non-Interventional Long-term Post-Marketing Registry of Patients Treated with Certolizumab Pegol (Cimzia®) for Crohn's Disease",
          "[Updt By: phiggins]",
          "UCB through a consortium with Schwarz Biosciences\tPI\t$87,800\t10/10\t02/20\tEdit\tDelete",
          "Patient Education on the Road",
          "[Updt By: phiggins]",
          "Takeda Pharmaceutical Company\tPI\t$0\t\t05/20\tEdit\tDelete",
          "Pfizer Consultant Agreement",
          "[Updt By: phiggins]",
          "Pfizer, Inc.\tPI\t$0\t\t01/21\tEdit\tDelete",
          "Healthcare Worker Exposure Response and Outcomes of Hydroxychloroquine Trial (HERO-HCQ Trial)",
          "[Updt By: Grants Load]",
          "Patient-Centered Outcomes Rese through a consortium with Duke University\tPI\t$640,500\t04/20\t09/20\tEdit\tDelete",
          "Dietary amino acids utilization by the gut microbiota in Crohn’s disease",
          "[Updt By: Grants Load]",
          "Kenneth Rainin Foundation\tCo-I with Effort\t$200,000\t03/20\t02/21\tEdit\tDelete",
          "Effect of intestinal infections on irritable bowel syndrome - diarrhea (IBS-D) Symptomatic activity",
          "[Updt By: Grants Load]",
          "BioFire\tPI\t$145,861\t05/18\t05/19\tEdit\tDelete",
          "Third Annual Patient Education on the Road Project",
          "[Updt By: Grants Load]",
          "Takeda Development Center\tPI\t$40,751\t03/18\t03/19\tEdit\tDelete",
          "Evaluation of the BH-3 mimetic ABT-737 as an anti-fibrotic drug in the Salmonella typhimurium mouse model of intestinal fibrosis",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$55,423\t12/17\t12/18\tEdit\tDelete",
          "Evaluation of the BH-3 mimetic ABT-737 as an anti-fibrotic drug in the rat TNBS model of intestinal fibrosis",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$68,883\t12/17\t12/18\tEdit\tDelete",
          "Evaluation of the BH-3 mimetic ABT-737 as an anti-fibrotic drug in human intestinal oganoids",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$44,276\t12/17\t12/18\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Risankizumab in Subjects with Moderately to Severely Active Crohn's Disease",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$0\t09/17\t12/20\tEdit\tDelete",
          "Sponsorship Agreement Project Number: SC#1000502837\tPatient Ed on the Road (Takeda Project Number: SC #1000502837)",
          "[Updt By: Grants Load]",
          "Takeda Pharmaceutical Company\tPI\t$28,421\t07/17\t07/18\tEdit\tDelete",
          "Clinical Study of the Buhlmann Fcal Elisa as an Aid in the Differentiation of Inflammatory Bowel Disease from Irritable Bowel Syndrome.",
          "[Updt By: Grants Load]",
          "Buhlmann Laboratories AG through a consortium with ICON Clinical Research, LLC\tPI\t$158,149\t06/17\t04/18\tEdit\tDelete",
          "Research Collaboration Agreement\tEffect of intestinal infections on inflammatory bowel disease activity",
          "[Updt By: Grants Load]",
          "BioFire\tPI\t$2,000\t05/17\t05/18\tEdit\tDelete",
          "A Randomized, Open-label, Parallel, Phase 2a Study to Determine the Tolerability, Pharmacokinetics, and Efficacy of APD371 in Subjects with Crohn’s disease experiencing Abdominal Pain",
          "[Updt By: Grants Load]",
          "Arena Pharmaceuticals, Inc.\tPI\t$40,190\t03/17\t03/18\tEdit\tDelete",
          "Clinical Study Agreement for APD371-004\tA Randomized, Open-label, Parallel, Phase 2a Study to Determine the Tolerability, Pharmacokinetics, and Efficacy of APD371 in Subjects with Crohn’s disease experiencing Abdominal Pain",
          "[Updt By: Grants Load]",
          "Arena Pharmaceuticals, Inc.\tPI\t$65,098\t03/17\t03/18\tEdit\tDelete",
          "Site Research Agreement for DINE-CD Study\tOpen Label, Randomized, Multicenter, Comparative Effectiveness Trial of Specific Carbohydrate and Mediterranean Diets to Induce Remission in Patients with Crohn's Disease",
          "[Updt By: debratan]",
          "Patient-Centered Outcomes Rese through a consortium with University of Pennsylvania\tPI\t$10,150\t03/17\t03/18\tEdit\tDelete",
          "A Phase 2, Multicenter, Randomized, Parallel-arm, Placebo-Controlled Study of LY3074828 in Subjects with Moderate to Severely Active Crohn's Disease Synopsis",
          "[Updt By: debratan]",
          "Lilly, Eli, and Company through a consortium with Quintiles, Inc\tPI\t$238,310\t03/17\t02/19\tEdit\tDelete",
          "A Phase 2, Multicenter, Randomized, Parallel-arm, Placebo-Controlled Study of LY3074828 in Subjects with Moderate to Severely Active Crohn's Disease Synopsis",
          "[Updt By: Grants Load]",
          "Eli Lilly and Company through a consortium with Quintiles, Inc\tPI\t$3,000\t03/17\t02/19\tEdit\tDelete",
          "A Randomized, Open-label, Parallel, Phase 2a Study to Determine the Tolerability, Pharmacokinetics, and Efficacy of APD371 in Subjects with Crohn's disease experiencing Abdominal Pain",
          "[Updt By: debratan]",
          "Arena Pharmaceuticals, Inc.\tPI\t$291,864\t03/17\t03/18\tEdit\tDelete",
          "Second Annual Patient2Patient Education Project",
          "[Updt By: Grants Load]",
          "Janssen Biotech, Inc.\tPI\t$4,000\t02/17\t06/17\tEdit\tDelete",
          "Clinical Trial Agreement - CRO for MOBIDIC Study\tMolecular Biomarkers and Adherent and Invasive Escherichia Coli (AIEC) Detection study In Crohn's disease patients (MOBIDIC)",
          "[Updt By: Grants Load]",
          "ENTEROME Bioscience through a consortium with ARIANNE Corporation\tPI\t$24,100\t02/17\t02/18\tEdit\tDelete",
          "A Randomized, Double-Blind, Placebo-Controlled Trial to Evaluate the Effectiveness of a Nutritional Intervention in Improving the Intestinal Mucosal Health Status in Subjects with Crohn's Disease (CD) Receiving Induction Anti-TNF Therapy PIONEER-CD",
          "[Updt By: debratan]",
          "Nestle HealthCare Nutrition, I through a consortium with Robarts Clinical Trials - Roba\tPI\t$71,632\t10/16\t08/17\tEdit\tDelete",
          "Phenotypical and quantitative analyses of leukocyte populations in matched blood and intestinal tissues in IBD patients and normal healthy patients",
          "[Updt By: Grants Load]",
          "Bristol-Myers Squibb Company\tPI\t$228,869\t09/16\t09/18\tEdit\tDelete",
          "Clinical Research Agreement for Protocol I6T-MC-AMAC under Master Clinical Trial\tA Phase 2, Multicenter, Randomized, Double-Blind, Parallel, Placebo-Controlled Study of LY3074828 in Subjects with Moderate to Severe Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Eli Lilly and Company\tPI\t$213,875\t07/16\t06/18\tEdit\tDelete",
          "5 R21 AI122098-02\tIn vivo photoacoustic biopsy for intestinal strictures in Crohn's disease",
          "[Updt By: Grants Load]",
          "NIH-DHHS-US\tPI\t$396,550\t07/16\t06/18\tEdit\tDelete",
          "A Phase 3, Randomized, Double-Blind, Placebo-Controlled, Multicenter Study To Investigate The Efficacy And Safety Of Mongersen (GED-0301) For The Treatment Of Subjects With Active Crohn's Disease",
          "[Updt By: debratan]",
          "Celgene Corporation through a consortium with Quintiles, Inc\tPI\t$104,298\t07/16\t06/18\tEdit\tDelete",
          "Sonosensitive Microdroplet Emulsions for Targeted Treatment of Crohn's Disease",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$2,500\t06/16\t08/16\tEdit\tDelete",
          "A Phase 2, Multi-Center, Open-Label Induction Trial with Extension Period to Assess Endoscopic Improvement and Changes in Intestinal and Serum Biomarkers in Patients with Moderately to Severely Active Crohn's Disease Receiving Oral RPC1063 as Induction Therapy",
          "[Updt By: Grants Load]",
          "Celgene Corporation through a consortium with Quintiles, Inc\tPI\t$189,517\t05/16\t04/18\tEdit\tDelete",
          "A Phase 3, Multicenter, Open-Label Extension Trial of Oral RPC1063 as Therapy for Moderate to Severe Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Celgene Corporation through a consortium with Quintiles, Inc\tPI\t$213,141\t03/16\t02/18\tEdit\tDelete",
          "SOW for M13-740 Celeste under Master CSA\tA Multicenter, Randomized, Double-Blind, Placebo-Controlled Study of ABT-494 for theInduction of Symptomatic and Endoscopic Remission in Subjects with Moderately to Severely Active Crohn's Disease who have Inadequately Responded to or are Intolerant to Anti-TNF Therapy",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$536,552\t03/16\t02/19\tEdit\tDelete",
          "IBD School Series of Videos",
          "[Updt By: Grants Load]",
          "Takeda Pharmaceutical Company\tPI\t$6,450\t03/16\t03/17\tEdit\tDelete",
          "A Phase 2b Double-blind, Multi-dose, Placebo-controlled Study to Evaluate the Efficacy and Safety of MEDI2070 in Subjects with Moderate to Severe Crohn’s Disease Who have Failed or Are Intolerant to Anti-tumor Necrosis Factor-alpha Therapy",
          "[Updt By: Grants Load]",
          "MedImmune LLC through a consortium with Quintiles, Inc\tPI\t$500\t02/16\t02/18\tEdit\tDelete",
          "A Phase 2b Double-blind, Multi-dose, Placebo-controlled Study to Evaluate the Efficacy and Safety of MEDI2070 in Subjects with Moderate to Severe Crohn's Disease Who Have Failed or Are Intolerant to Anti-tumor Necrosis Factor-alpha Therapy",
          "[Updt By: debratan]",
          "MedImmune, Inc. through a consortium with Quintiles, Inc\tPI\t$282,198\t02/16\t02/18\tEdit\tDelete",
          "A Phase 2, Open-Label, Multicenter Study to Explore the Efficacy and Safety of Mongersen (GED-0301) in Subjects with Active Ulcerative Colitis",
          "[Updt By: debratan]",
          "Celgene Corporation\tPI\t$85,755\t02/16\t01/17\tEdit\tDelete",
          "Clinical Trial Agreement for GS-US-326-1100\tA Combined Phase 2/3, Double-Blind, Randomized, Placebo-Controlled, Induction and Maintenance Study Evaluating the Safety and Efficacy of GS-5745 in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Gilead Sciences, Inc. through a consortium with Icon, Inc.\tPI\t$191,676\t01/16\t12/17\tEdit\tDelete",
          "IBD School Web 200-Video Series - Advanced Topics",
          "[Updt By: Grants Load]",
          "Janssen Pharmaceuticals, Inc.\tPI\t$14,835\t01/16\t12/16\tEdit\tDelete",
          "CCFA Recruitment Initiative",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$13,235\t01/16\t01/17\tEdit\tDelete",
          "EPIC IBD SmartForm Pilot Study",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with University of Pennsylvania\tPI\t$9,000\t01/16\t12/16\tEdit\tDelete",
          "A Phase 3, Multicenter, Randomized, Double-blind, Placebo controlled Trial of Oral RPC1063 as Induction and Maintenance Therapy for Moderate to Severe Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Receptos, Inc. through a consortium with Quintiles, Inc\tPI\t$134,508\t11/15\t08/17\tEdit\tDelete",
          "A Randomized, Double-Blind, Multicenter Study To Explore The Effect Of GED-0301 On Endoscopic And Clinical Outcomes In Subjects With Active Crohn's Disease",
          "[Updt By: debratan]",
          "Celgene Corporation\tPI\t$128,049\t11/15\t09/18\tEdit\tDelete",
          "5-ASA to Sulfasalazine, a Cost Saving Drug Switch",
          "[Updt By: Grants Load]",
          "BCBSF\tPI\t$70,871\t09/15\t08/16\tEdit\tDelete",
          "An Open-Label Phase 3b Study to Assess Mucosal Healing in Subjects With Moderately to Severely Active Crohn's Disease Treated With Vedolizumab IV",
          "[Updt By: debratan]",
          "Takeda Global Research and Dev through a consortium with Quintiles, Inc\tPI\t$99,742\t08/15\t07/17\tEdit\tDelete",
          "Clinical Trial Agreement for GS-US-395-1663\tA Phase 2, Double-blind, Randomized, Placebo-Controlled, Multicenter Study Evaluating the Safety and Efficacy of GS-5745 in Subjects with Moderately to Severely Active Crohn's Disease",
          "[Updt By: debratan]",
          "Gilead Sciences, Inc. through a consortium with ICON Clinical Research, Inc.\tPI\t$129,168\t07/15\t07/18\tEdit\tDelete",
          "SOW Protocol GA29144\tA phase III, randomized, double-blind, placebo-controlled, multicenter study to evaluate the efficacy and safety of etrolizumab as an induction and maintenance treatment for patients with moderately to severely active Crohn's disease",
          "[Updt By: debratan]",
          "Genentech, Inc. through a consortium with Quintiles, Inc\tPI\t$3,780\t04/15\t03/18\tEdit\tDelete",
          "Mucosal Healing and Relapse in Quiescent Ulcerative Colitis: An Exploratory Study (Marquee) Study extension",
          "[Updt By: debratan]",
          "Crohn's and Colitis Foundation through a consortium with University of Pennsylvania\tPI\t$4,620\t04/15\t07/16\tEdit\tDelete",
          "CCFA Clinical Research Alliance co-chair",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with University of North Carolina a\tPI\t$26,212\t03/15\t06/16\tEdit\tDelete",
          "1000307312\tPatient Ed on the Road- Takeda",
          "[Updt By: Grants Load]",
          "Takeda Pharmaceuticals USA\tPI\t$17,000\t02/15\t02/16\tEdit\tDelete",
          "IBD School Web Series 200 series- advanced topics",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$12,255\t02/15\t12/15\tEdit\tDelete",
          "A Double-Blind, Placebo-Controlled, Parallel-Group, Multicenter, Multiregional, One Year Study to Assess the Efficacy and Safety of Twice Daily Oral Rifaximin Delayed Release Tablets for Induction of Clinical Remission with Endoscopic Response at 16 Weeks followed by Clinical and Endoscopic Remission at 52 Weeks in Subjects with Active Moderate Crohn's Disease",
          "[Updt By: debratan]",
          "Salix Pharmaceuticals, Inc\tPI\t$195,094\t01/15\t12/17\tEdit\tDelete",
          "Autoimmune Paradoxical Reactions in IBD Longitudinal cohort (APRIL Cohort)",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with University of North Carolina a\tPI\t$13,200\t12/14\t12/15\tEdit\tDelete",
          "Statement of Work for GA28949 under Master Clinical Study Agreement\tPhase III, Randomized, Double-Blind, Double-Dummy, Placebo-Controlled, Multicenter Study to Evaluate the Efficacy for (Induction of Remission) and Safety of Etrolizumab Compared with Placebo in Patients with Moderate to Severe Ulcerative Colitis Who are NaÔve to TNF Inhibitors - GA28949",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with Quintiles, Inc\tPI\t$160,636\t12/14\t10/18\tEdit\tDelete",
          "Research Agreement\tAdditional funds for Evaluation of ROCK 1 and ROCK 2 inhibitors using models of intestinal fibrosis",
          "[Updt By: Grants Load]",
          "Lycera Corporation\tPI\t$6,284\t12/14\t08/16\tEdit\tDelete",
          "A Multicenter, Open-Label Study to Evaluate the Long Term Efficacy, Safety and Tolerability of Repeated Administration of Adalimumab in Subjects with Crohn's Disease",
          "[Updt By: debratan]",
          "AbbVie Inc through a consortium with INC Research\tPI\t$188,475\t10/14\t09/18\tEdit\tDelete",
          "Clinical Study Agreement Protocol M14-033\tDouble-Blind, Randomized, Multicenter Study of Higher Versus Standard Adalimumab Dosing Regimens for Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "AbbVie, Inc. through a consortium with INC Research\tPI\t$85,247\t09/14\t08/17\tEdit\tDelete",
          "A Multicenter Open-Label Extension Study to Assess Long-Term Safety of PF-00547659 in Subjects With Ulcerative Colitis TURANDOT II)",
          "[Updt By: debratan]",
          "Pfizer Incorporated through a consortium with ICON Clinical Research, Inc.\tPI\t$47,032\t09/14\t02/19\tEdit\tDelete",
          "Clinical Trial Agreement & Letter of Indemnification for Protocol CT-P13 3.4\tA Randomized, Double-Blind, Parallel-Group, Phase 3 Study to Demonstrate Noninferiority in Efficacy and to Assess Safety of CT-P13 Compared to Remicade in Patients With Active Crohn's Disease",
          "[Updt By: debratan]",
          "Celltrion through a consortium with PPD, Inc.\tPI\t$293,964\t09/14\t10/17\tEdit\tDelete",
          "Evaluation of ROCK 1 and ROCK 2 inhibitors using models of intestinal fibrosis",
          "[Updt By: Grants Load]",
          "Lycera Corporation\tPI\t$34,787\t09/14\t08/15\tEdit\tDelete",
          "Clinical Study Agreement & Letter of Indemnification for Protocol M14-033\tDouble-Blind, Randomized, Multicenter Study of Higher Versus Standard Adalimumab Dosing Regimens for Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "AbbVie, Inc. through a consortium with INC Research\tPI\t$392,099\t08/14\t08/17\tEdit\tDelete",
          "Evaluating a Prediction Tool and Decision Aid for Patients with Crohn's Disease",
          "[Updt By: debratan]",
          "SubK-AHCRQ-DHHS-US through a consortium with Dartmouth College\tPI\t$15,750\t08/14\t07/16\tEdit\tDelete",
          "A Randomized Controlled Trial of High Dose Vitamin D Therapy in Crohn's Disease (RODIN-CD)",
          "[Updt By: debratan]",
          "Crohn's and Colitis Foundation\tPI\t$110,000\t08/14\t07/15\tEdit\tDelete",
          "Phase III, Double Blind, Placebo-Controlled Multicenter Study of the Efficacy and Safety of Etrolizumab During Induction and Maintenance in Patients with Moderate to Severe Active Ulcerative Colitis Who are Refractory to or Intolerant of TNF Inhibitors",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with Quintiles, Inc\tPI\t$206,291\t07/14\t09/18\tEdit\tDelete",
          "SOW for Protocol# GA28950\tPhase III, Double Blind, Placebo-Controlled Multicenter Study of the Efficacy and Safety of Etrolizumab During Induction and Maintenance in Patients with Moderate to Severe Active Ulcerative Colitis Who are Refractory to or Intolerant of TNF Inhibitors",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with Quintiles, Inc\tPI\t$111,246\t07/14\t09/18\tEdit\tDelete",
          "A Phase 2b, Multicenter, Randomized, Double-blind, Placebo-controlled, Parallel-group, Doseresponse Study Evaluating the Efficacy and Safety of JNJ-54781532 in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Janssen Research and Developme through a consortium with Research Pharmaceuticals Servi\tPI\t$252,543\t06/14\t06/18\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind Study to Evaluate the Efficacy and Safety of Two Adalimumab Induction Regimens in Subjects with Moderately to Severely Active Crohn's Disease and Evidence of Mucosal Ulceration",
          "[Updt By: Grants Load]",
          "AbbVie, Inc. through a consortium with INC Research\tPI\t$372,020\t06/14\t05/16\tEdit\tDelete",
          "A Randomized, Double-Blind, Placebo-Controlled, Parallel Group, Multi-Centre Study to Investigate the Safety and Efficacy of CP-690,550 for Maintenance Therapy in Subjects with Moderate to Severe Crohn's Disease",
          "[Updt By: debratan]",
          "Pfizer Incorporated through a consortium with ICON Clinical Research, Inc.\tPI\t$50,546\t04/14\t03/16\tEdit\tDelete",
          "A Open-Label Extension Study of CP-690,550 as Maintenance Therapy in Patients with Crohn's Disease",
          "[Updt By: debratan]",
          "Pfizer Incorporated through a consortium with ICON Clinical Research, Inc.\tPI\t$49,922\t04/14\t03/16\tEdit\tDelete",
          "Serum glycoproteome profiling to detect intestinal fibrosis in stricturing Crohn's disease",
          "[Updt By: debratan]",
          "Broad, Eli and Edythe L., Foun\tPI\t$216,209\t04/14\t03/16\tEdit\tDelete",
          "Renal failure rates in IBD patients and associated complications",
          "[Updt By: Grants Load]",
          "AMAG Pharmaceuticals, Inc\tPI\t$8,588\t03/14\t07/14\tEdit\tDelete",
          "Prospective Cohort of Ulcerative Colitis and Crohn's Disease Patients Undergoing Surgery to Identify Risk Factors for Post-Operative Infection I (PUCCINI)",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with Icahn School of Med Mt Sinai\tPI\t$18,750\t02/14\t01/17\tEdit\tDelete",
          "Study Order Pfizer Protocol #A3921083\tA Randomized, Double-Blind, Placebo-Controlled, Parallel Group, Multi-Centre, Study to Investigate the Safety and Efficacy of CP-690,550 for Induction Therapy in subjects with Moderate to Severe Crohn's Disase",
          "[Updt By: debratan]",
          "Pfizer through a consortium with ICON Clinical Research, Inc.\tPI\t$148,144\t02/14\t12/15\tEdit\tDelete",
          "Clinical Trial Agreement Order to Master Protocol 20110232\tA Randomized, Double-blind, Placebo-controlled Study to Evaluate the Safety, Tolerability, and Efficacy of AMG 181 in Subjects with Moderate to Severe Crohn's Disease",
          "[Updt By: debratan]",
          "Amgen, Inc.\tPI\t$203,842\t12/13\t11/17\tEdit\tDelete",
          "Clinical Trial Agreement Order to Master Protocol 20110232\tA Randomized, Double-blind, Placebo-controlled Study to Evaluate the Safety, Tolerability, and Efficacy of AMG 181 in Subjects with Moderate to Severe Crohn's Disease",
          "[Updt By: debratan]",
          "Amgen, Inc.\tPI\t$1,170\t12/13\t11/17\tEdit\tDelete",
          "Mucosal Healing and Relapse in Quiescent Ulcerative Colitis: An Exploratory Study (Marquee) Study",
          "[Updt By: debratan]",
          "Crohn's and Colitis Foundation through a consortium with University of Pennsylvania\tPI\t$9,240\t10/13\t09/15\tEdit\tDelete",
          "A Multicenter Study Evaluating a Practical Index Score for Subjects with Crohn's DIsease Assessing the Absence of Mucosal Ulceration (PREDICT)",
          "[Updt By: debratan]",
          "AbbVie Inc through a consortium with Clinipace\tPI\t$45,884\t10/13\t09/14\tEdit\tDelete",
          "Study Order to Protocol #A7281010\tA Multicenter Open-Label Extension Study to Assess Long-Term Safety of PF-00547659 in Subjects with Ulcerative Colitis (TURANDOT II)",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$468,083\t09/13\t08/17\tEdit\tDelete",
          "Award Letter dated 6/25/2013\tAlgorithms for CT Use in the ED in Crohn's Disease",
          "[Updt By: debratan]",
          "Inflammatory Bowel Disease Wor\tPI\t$40,000\t07/13\t06/14\tEdit\tDelete",
          "Clinical Study Agreement to Study Drug MEDI2070\tA Phase 2a Study to Evaluate the Efficacy and Safety of MEDI2070 in Subjects with Moderate to Severe Crohn's Disease Who Have Failed or Are Intolerant to Anti-tumor Necrosis Factor-alpha Therapy, D5170C00001",
          "[Updt By: debratan]",
          "AstraZeneca, PLC\tPI\t$311,832\t06/13\t10/15\tEdit\tDelete",
          "Study Order to Master Protocol #A7281009\tPFIZER PROTOCOL #A7281009 PROTOCOL TITLE: A Double-Blind, Randomized, Placebo-Controlled, Parallel, Dose-Ranging Study to Evaluate the Efficacy and Safety of PF-00547659 in Subjects with Moderate to Severe Ulcerative Colitis (TURANDOT)",
          "[Updt By: debratan]",
          "Pfizer Incorporated through a consortium with ICON Clinical Research, Inc.\tPI\t$214,527\t03/13\t09/15\tEdit\tDelete",
          "A study to define the sensitivity and responsiveness of circulating T cells in subjects with inflammatory bowel disease (IBD), specifically Crohn's disease (CD) and ulcerative colitis (UC), to an anti-inflammatory F1FO ATPase inhibitor.",
          "[Updt By: debratan]",
          "Lycera Corporation\tPI\t$50,160\t02/13\t06/16\tEdit\tDelete",
          "A study to define the sensitivity and responsiveness of circulating T cells in subjects with inflammatory bowel disease (IBD), specifically Crohn’s disease (CD) and ulcerative colitis (UC), to an anti-inflammatory F1FO ATPase inhibitor.",
          "[Updt By: Grants Load]",
          "Lycera Corporation\tPI\t$4,992\t02/13\t01/15\tEdit\tDelete",
          "A study to define the sensitivity and responsiveness of circulating T cells in subjects with inflammatory bowel disease (IBD), specifically Crohn’s disease (CD) and ulcerative colitis (UC), to an anti-inflammatory F1FO ATPase inhibitor.",
          "[Updt By: Grants Load]",
          "Lycera Corporation\tPI\t$29,960\t02/13\t01/14\tEdit\tDelete",
          "Appendix D\tA study to define the sensitivity and responsiveness of circulating T cells in subjects with inflammatory bowel disease (IBD), specifically Crohn's disease (CD) and ulcerative colitis (UC), to an anti-inflammatory F1FO ATPase inhibitor.",
          "[Updt By: debratan]",
          "Lycera Corporation\tPI\t$24,607\t02/13\t08/13\tEdit\tDelete",
          "CCFA Ref. #253590\tClostridium difficile infection induces changes in the gut microbiome that lead to IBD flares",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$347,490\t01/13\t12/15\tEdit\tDelete",
          "CTA for Protocol CNDO-201-003\tA Phase II Study to Evaluate the Efficacy and Safety of 12 Weeks of Treatment with Oral CNDO 201 Trichuris Suis Ova Suspension (TSO) as Compared to Placebo, Followed By a 12 week Open-Label Treatment Period in Patients with Moderately to Severely Active Crohn's Disease",
          "[Updt By: debratan]",
          "Coronado Biosciences, Inc through a consortium with United BioSource Corporation (\tPI\t$194,656\t12/12\t12/14\tEdit\tDelete",
          "Inter-Institutional Agreement\tGEM Project-A Multidisciplinary Human Study on the Genetic, Environmental and Microbial Interactions that Cause Inflammatory Bowel Disease",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with Mount Sinai Hospital\tPI\t$55,000\t10/12\t09/16\tEdit\tDelete",
          "Study IIS-US-0095: Contrast-Enhanced Ultrasound Assessment of Inflamed vs. Fibrotic Bowel Segments in a Crohn Disease Animal Model",
          "[Updt By: Grants Load]",
          "Bracco Diagnostics, Inc.\tCo-I with Effort\t$29,900\t09/12\t10/13\tEdit\tDelete",
          "Contrast-Enhanced Ultrasound Assessment of Inflamed vs. Fibrotic Bowel Segments in a Crohn Disease Animal Model",
          "[Updt By: Grants Load]",
          "Siemens Medical Solutions USA,\tCo-I with Effort\t$29,900\t09/12\t08/13\tEdit\tDelete",
          "4 R01 GM097117-05\tApplication of Machine Learning Algorithms to Thiopurine Monitoring in IBD",
          "[Updt By: Grants Load]",
          "NIH-DHHS-US\tPI\t$1,936,522\t08/12\t04/17\tEdit\tDelete",
          "Ultrasound Stiffness Imaging for the Differentiation of Intestinal Fibrosis from Inflammation in Crohn's Disease",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$270,000\t07/12\t07/15\tEdit\tDelete",
          "Study Order to Pfizer Protocol # A3921139\tA Multi-Center, Open-Label, Study of CP-690,550 In Subjects With Moderate To Severe Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$258,301\t06/12\t06/17\tEdit\tDelete",
          "A MULTICENTRE, RANDOMIZED, DOUBLE-BLIND, PLACEBO-CONTROLLED, PARALLEL-GROUP STUDY OF ORAL CP-690,550 AS A MAINTENANCE THERAPY IN SUBJECTS WITH ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$168,774\t05/12\t05/16\tEdit\tDelete",
          "Study Order under Master for Protocol A3921094\tA MULTICENTRE, RANDOMIZED, DOUBLE-BLIND, PLACEBO-CONTROLLED, PARALLEL-GROUP STUDY OF ORAL CP-690,550 AS AN INDUCTION THERAPY IN SUBJECTS WITH MODERATE TO SEVERE ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$8,450\t05/12\t04/15\tEdit\tDelete",
          "A MULTICENTRE, RANDOMIZED, DOUBLE-BLIND, PLACEBO-CONTROLLED, PARALLEL-GROUP STUDY OF ORAL CP-690,550 AS AN INDUCTION THERAPY IN SUBJECTS WITH MODERATE TO SEVERE ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$111,410\t05/12\t04/14\tEdit\tDelete",
          "Study Order under Master for Protocol A3921094\tA MULTICENTRE, RANDOMIZED, DOUBLE-BLIND, PLACEBO-CONTROLLED, PARALLEL-GROUP STUDY OF ORAL CP-690,550 AS AN INDUCTION THERAPY IN SUBJECTS WITH MODERATE TO SEVERE ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Pfizer, Inc. through a consortium with ICON Clinical Research, LLC\tPI\t$13,113\t05/12\t04/14\tEdit\tDelete",
          "A Phase 3, Open-label Study to Determine the Long-Term Safety and Efficacy of Vedolizumab (MLN0002) in Patients with Ulcerative Colitis and Crohn's Disease",
          "[Updt By: debratan]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$621,490\t05/12\t04/19\tEdit\tDelete",
          "Calprotectin-Directed Humira® Maintenance Therapy, a Double-blind, Double-dummy, Randomized Controlled Trial in Crohn's Disease (CADHUM) Abbott IMM 10-0105",
          "[Updt By: debratan]",
          "AbbVie Inc\tPI\t$115,451\t05/12\t04/15\tEdit\tDelete",
          "Calprotectin-Directed Humira® Maintenance Therapy, a Double-blind, Double-dummy, Randomized Controlled Trial in Crohn's Disease (CADHUM) Abbott IMM 10-0105",
          "[Updt By: debratan]",
          "Abbott Laboratories\tPI\t$420,188\t05/12\t04/14\tEdit\tDelete",
          "Clinical Trial Agreement\tA Phase 3, Randomized, Placebo-Controlled, Blinded, Multicenter Study of the Induction of Clinical Response and Remission by Vedolizumab in Patients with Moderate to Severe Crohn's Disease",
          "[Updt By: debratan]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$1,500\t05/12\t04/14\tEdit\tDelete",
          "SOW # GA28084 to the Master Clinical Research Agreement\tObservational Multicenter Study in Patients with Crohn's Disease for Characterization of Magnetic Resonance Enterography Assays for Assessment of Disease Activity",
          "[Updt By: debratan]",
          "PPD, Inc. through a consortium with Genentech, Inc.\tPI\t$80,119\t04/12\t03/13\tEdit\tDelete",
          "SOW # GA28084 to the Master Clinical Research Agreement\tObservational Multicenter Study in Patients with Crohn's Disease for Characterization of Magnetic Resonance Enterography Assays for Assessment of Disease Activity Amendment",
          "[Updt By: debratan]",
          "Genentech, Inc. through a consortium with PPD, Inc.\tPI\t$6,500\t04/12\t03/13\tEdit\tDelete",
          "A PHASE II OPEN-LABEL EXTENSION STUDY TO EVALUATE THE LONG-TERM SAFETY OF rhuMAb BETA7 IN PATIENTS WITH MODERATE TO SEVERE ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with Pharmaceutical Product Develop\tPI\t$334,617\t03/12\t02/16\tEdit\tDelete",
          "Prospective Cohort of Ulcerative Colitis and Crohn's Disease Patients Undergoing Surgery to Identify Risk Factors for Post-Operative Infection I (PUCCINI)",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with Mount Sinai Medical Center, Th\tPI\t$19,249\t03/12\t02/13\tEdit\tDelete",
          "CTA to Protocol 1275CRD3003 & LOI\tA Phase 3, Multicenter, Randomized, Placebo controlled, Double-blind Study to Evaluate the Safety and Efficacy of Ustekinumab Maintenance Therapy in Subjects with Moderately to Severely Active Crohn's Disease Protocol CNTO1275CRD3003",
          "[Updt By: debratan]",
          "Janssen Research and Developme through a consortium with Paraxel\tPI\t$414,339\t02/12\t10/14\tEdit\tDelete",
          "A Phase 3, Multicenter, Randomized, Placebo controlled, Double-blind Study to Evaluate the Safety and Efficacy of Ustekinumab Maintenance Therapy in Subjects with Moderately to Severely Active Crohn's Disease Protocol CNTO1275CRD3003",
          "[Updt By: debratan]",
          "Janssen Research and Developme through a consortium with Paraxel\tPI\t$789,580\t02/12\t10/14\tEdit\tDelete",
          "PHASE II RANDOMIZED DOUBLE-BLIND PLACEBO-CONTROLLED STUDY TO EVALUATE THE EFFICACY AND SAFETY OF rhuMAb BETA7 IN PATIENTS WITH MODERATE TO SEVERE ULCERATIVE COLITIS",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with PPD Development, LP\tPI\t$304,518\t01/12\t12/14\tEdit\tDelete",
          "CTA & LOI to Protocol CNTO1275-CRD-3002\tA Phase 3, Randomized, Double-blind, Placebo-controlled, Parallel-group, Multicenter Study to Evaluate the Safety and Efficacy of Ustekinumab Induction Therapy in Subjects with Moderately to Severely Active Crohn's Disease (study 3002)",
          "[Updt By: debratan]",
          "Janssen Biotech, Inc. through a consortium with Paraxel\tPI\t$111,207\t01/12\t10/14\tEdit\tDelete",
          "CTA to ProtocolCNTO1275CRD3001 & Letter of Indemnification\tA Phase 3, Randomized, Double-blind, Placebo-controlled, Parallel-group, Multicenter Study to Evaluate the Safety and Efficacy of Ustekinumab Induction Therapy in Subjects with Moderately to Severely Active Crohn's Disease Who Have Failed or Are Intolerant to TNF Antagonist Therapy (3001 study)",
          "[Updt By: debratan]",
          "Janssen Biotech, Inc. through a consortium with Paraxel\tPI\t$111,207\t12/11\t10/14\tEdit\tDelete",
          "CTA to Protocol C13008\tA Phase 3, Open-label Study to Determine the Long-Term Safety and Efficacy of Vedolizumab (MLN0002) in Patients with Ulcerative Colitis and Crohn's Disease",
          "[Updt By: Grants Load]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$1,500\t09/11\t04/19\tEdit\tDelete",
          "A Phase 3, Open-label Study to Determine the Long-Term Safety and Efficacy of Vedolizumab (MLN0002) in Patients with Ulcerative Colitis and Crohn's Disease (Millenium C13008 amendment for travel costs)",
          "[Updt By: debratan]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$41,670\t09/11\t07/16\tEdit\tDelete",
          "A Phase 3, Randomized, Double-blind, Placebo-controlled, Parallel-group, Multicenter Study to Evaluate the Safety and Efficacy of Ustekinumab Induction Therapy in Subjects with Moderately to Severely Active Crohn's Disease Who Have Failed or Are Intolerant to TNF Antagonist Therapy (3001 study) Amendment",
          "[Updt By: debratan]",
          "Janssen Research and Developme through a consortium with Paraxel\tPI\t$84,910\t09/11\t02/14\tEdit\tDelete",
          "5 R01 DK055732-14\tMechanisms of Gastrointestinal Growth and Transformation",
          "[Updt By: Grants Load]",
          "NIH-DHHS-US\tCo-I without Effort\t$1,380,347\t08/11\t07/15\tEdit\tDelete",
          "Research Agreement\tBuhlmann Calprotectin ELISA method comparison to predictive device for FDA clearance",
          "[Updt By: Grants Load]",
          "Buhlmann Laboratories AG\tPI\t$32,524\t08/11\t07/14\tEdit\tDelete",
          "Research Agreement\tBuhlmann Calprotectin ELISA method comparison to predictive device for FDA clearance",
          "[Updt By: Grants Load]",
          "Buhlmann Laboratories AG\tPI\t$209,154\t08/11\t07/12\tEdit\tDelete",
          "Schedule A, Appendix 11\tProtocol C13008 - A Phase 3, Open-label Study to Determine the Long-Term Safety and Efficacy of Vedolizumab (MLN0002) in Patients with Ulcerative Colitis and Crohn's Disease",
          "[Updt By: debratan]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$275,810\t08/11\t07/16\tEdit\tDelete",
          "Subaward 555891\tCCFA Clinical Research Alliance co-chair",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation through a consortium with University of North Carolina a\tPI\t$22,000\t07/11\t06/12\tEdit\tDelete",
          "Clinical Study Agreement\tA 52 week Randomised, Double-blind, Placebo-controlled Study to Investigate the Efficacy and Safety of GSK1605786A in the Maintenance of Remission in Subjects with Crohn’s Disease (GSK 157 amendment 1 additional funds)",
          "[Updt By: Grants Load]",
          "GSK through a consortium with Robarts Clinical Trials - Roba\tPI\t$375\t06/11\t05/13\tEdit\tDelete",
          "Exhibit C - Form Study Specific Agreement\tProtocol CCX114644, An Open-Label Extension Study to Assess the Safety of GSK1605786A in Subjects with Crohn's Disease",
          "[Updt By: debratan]",
          "GSK through a consortium with Robarts Clinical Trials - Roba\tPI\t$152,575\t06/11\t05/14\tEdit\tDelete",
          "Exhibit B - Form Study Specific Agreement\tProtocol CCX114157, entitled ¿A 52 week Randomised, Double-blind, Placebo-controlled Study to Investigate the Efficacy and Safety of GSK1605786A in the Maintenance of Remission in Subjects with Crohn's Disease¿",
          "[Updt By: debratan]",
          "GSK through a consortium with Robarts Clinical Trials - Roba\tPI\t$116,139\t06/11\t05/13\tEdit\tDelete",
          "Appendix 10 to MCTA\tVedolizumab in Patients with Moderate to Severe Crohn's Disease - Additional funds GEMINI study",
          "[Updt By: Grants Load]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$3,654\t05/11\t04/12\tEdit\tDelete",
          "Appendix 10 to MCTA\tA Phase 3, Randomized, Placebo-Controlled, Blinded, Multicenter Study of the Induction of Clinical Response and Remission by Vedolizumab in Patients with Moderate to Severe Crohn's Disease",
          "[Updt By: Grants Load]",
          "Millennium Pharmaceuticals, In through a consortium with Quintiles, Inc\tPI\t$47,081\t04/11\t04/12\tEdit\tDelete",
          "Clinical Trial Agreement\tA Randomized Double-blind, Placebo-Controlled Study to Investigate the Efficacy and Safety of GSK1605786A in the Treatment of Subjects with Moderately to Severely Active Crohn's Disease (GSK 151 amendment 1, additional funds)",
          "[Updt By: debratan]",
          "GSK through a consortium with Robarts Clinical Trials - Roba\tPI\t$12,725\t04/11\t03/13\tEdit\tDelete",
          "Clinical Trial Site Agreement\tA Randomized Double-blind, Placebo-Controlled Study to Investigate the Efficacy and Safety of GSK1605786A in the Treatment of Subjects with Moderately to Severely Active Crohn's Disease Protocol CCX114151",
          "[Updt By: debratan]",
          "GSK through a consortium with Robarts Clinical Trials - Roba\tPI\t$99,125\t02/11\t03/13\tEdit\tDelete",
          "CTA to Protocol# REMICADECRD3001\tAmendment #1 - Prospective, Multicenter, Randomized, Double-Blind, Placebo-Controlled Trial Comparing REMICADE (Infliximab) and Placebo in the Prevention of Recurrence in Crohn's Disease Patients Undergoing Surgical Resection Who Are at an Increased Risk of Recurrence",
          "[Updt By: Grants Load]",
          "Janssen Services, L.L.C. through a consortium with Paraxel\tPI\t$344,900\t01/11\t06/14\tEdit\tDelete",
          "CTA to Protocol#REMICADECRD3001\tProspective, Multicenter, Randomized, Double-Blind, Placebo-Controlled Trial Comparing REMICADE® (infliximab) and Placebo in the Prevention of Recurrence in Crohn's Disease Patients Undergoing Surgical Resection Who Are at an Increased Risk of Recurrence",
          "[Updt By: debratan]",
          "Janssen Biotech, Inc. through a consortium with Paraxel\tPI\t$224,553\t01/11\t06/14\tEdit\tDelete",
          "Letter of Agreement\tIBD School: A Series of Patient Education Web Videos on Inflammatory Bowel Disease",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$30,000\t10/10\t12/11\tEdit\tDelete",
          "Educational Grant Agreement dtd 8/23/2010\tIBD School: A Series of Patient Education Videos about Inflammatory Bowel Disease",
          "[Updt By: Grants Load]",
          "Janssen Services, L.L.C.\tPI\t$37,000\t10/10\t12/11\tEdit\tDelete",
          "Email dated 5/24/2010\tInvestigating Ultrasound Elasticity Imaging in Assessment of Intestinal Fibrosis in Crohn's Disease",
          "[Updt By: Grants Load]",
          "UCB BioPharma SPRL through a consortium with Crohn's Disease Working Group\tPI\t$40,000\t07/10\t06/11\tEdit\tDelete",
          "CTA to Protocol# C0524T18\tProtocol C0524T18 A Phase 3 Multicenter, Randomized, Placebo-controlled, Double-blind Study to Evaluate the Safety and Efficacy of Golimumab Maintenance Therapy, Administered Subcutaneously, in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Janssen Research and Developme through a consortium with Quintiles, Inc\tPI\t$165,055\t04/10\t12/14\tEdit\tDelete",
          "CTA to Protocol# C0524T18\tCentocor T17 amendment 1",
          "[Updt By: Grants Load]",
          "Janssen Biotech, Inc. through a consortium with Quintiles, Inc\tPI\t$2,116\t04/10\t12/14\tEdit\tDelete",
          "CTA to Protocol# C0524T17\tProtocol C0524T17 A Phase 2/3 Multicenter, Randomized, Placebo-controlled, Double-blind Study to Evaluate the Safety and Efficacy of Golimumab Induction Therapy, Administered Subcutaneously, in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Janssen Research and Developme through a consortium with Quintiles, Inc\tPI\t$73,988\t04/10\t11/10\tEdit\tDelete",
          "Material Transfer Agreement\tNovel Biomarkers of Intestinal Inflammation and Fibrosis in Crohn's Disease",
          "[Updt By: debratan]",
          "Pfizer Incorporated\tPI\t$23,500\t03/10\t03/12\tEdit\tDelete",
          "Collaboration Agreement\tUlcerative Colitis PRO Development Protocol",
          "[Updt By: Grants Load]",
          "Genentech, Inc.\tPI\t$375,000\t12/09\t02/12\tEdit\tDelete",
          "Original Agreement\tCD PRO Development Protocol, Supplement to N011938",
          "[Updt By: Grants Load]",
          "Genentech, Inc.\tPI\t$455,000\t12/09\t02/11\tEdit\tDelete",
          "Clinical Trial Research Agreement to rotocol C0743T26 dtd7/9/2009\tThe Phase 2B, Multicenter, Randomized, Double-blind, Placebo-controlled, Parallel-group Study to Evaluate the Efficacy and Safety of Ustekinumab Therapy in Subjects with Moderately to Severly Active Crohn's Disease Previously Treated with TNF Antagonist Therapy",
          "[Updt By: Grants Load]",
          "Janssen Biotech, Inc. through a consortium with Kendle International Inc.\tPI\t$700\t07/09\t06/11\tEdit\tDelete",
          "Clinical Trial/Resesarch Agreement to Protocol# C0743T26\tA Phase 2B, Multicenter, Randomized, Double-blind, Placebo-controlled, Parallel-group Study to Evaluate the Efficacy and Safety of Ustekinumab Therapy in Subjects with Moderately to Severly Active Crohn's Disease Previously Treated with TNF Antagonist Therapy",
          "[Updt By: Grants Load]",
          "Janssen Biotech, Inc. through a consortium with Kendle International Inc.\tPI\t$45,519\t07/09\t06/11\tEdit\tDelete",
          "2488\tA Mechanism for the Auto-propagation of Human Fibroblast Cells",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$2,500\t06/09\t08/09\tEdit\tDelete",
          "Clinical Research Agreement dtd 3/25/2009\tObservational Study of Biomarkers in Subjects with Inflammatory Bowel Disease (IBD) Compared with Non-IBD Control Subjects",
          "[Updt By: Grants Load]",
          "Genentech, Inc.\tPI\t$227,178\t03/09\t11/10\tEdit\tDelete",
          "Clinical Study Agreement\tAn Observational Prospective Study to Identify Clinical, Endoscopic, and/or Biological Predictors that Correlate with Histopathologic Findings in Subjects with Moderate to Severe Ulcerative colitis",
          "[Updt By: Grants Load]",
          "Otsuka America Pharmaceutical, through a consortium with Robarts Clinical Trials - Roba\tPI\t$30,652\t06/08\t06/09\tEdit\tDelete",
          "Clinical Trial Request Form AIN457A2202\tA Multicenter, Randomized, Double- Blind, Placebo Controlled, Parallel Group Proof of Concept Study to Assess the Efficacy, Safety and Tolerability of Two Single IV Infusions of AIN457 10 mg/kg (Anti IL-17 Monoclonal Antibody) in Patients with Moderate to Severe Active Crohn's Disease",
          "[Updt By: Grants Load]",
          "Novartis AG\tPI\t$111,186\t03/08\t11/09\tEdit\tDelete",
          "5 K08 DK080172-03\tMechanisms and Prevention of TGF-Beta-Induced Intestinal Fibrosis",
          "[Updt By: Grants Load]",
          "NIH-DHHS-US\tPI\t$460,080\t02/08\t01/11\tEdit\tDelete",
          "Award letter dated 11/26/07\tSheathed vs. Standard Forceps: Does it Matter for Obtaining Uncontaminated Biopsy Specimen of Microbiota from the Terminal Ileum?",
          "[Updt By: Grants Load]",
          "ASGE\tPI\t$20,000\t01/08\t09/09\tEdit\tDelete",
          "Ck# 4456\tThe Perception of Colon Cancer Risk in Patients with Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Procter & Gamble Co.\tPI\t$14,828\t01/08\t08/08\tEdit\tDelete",
          "Payment Request Form\tIBD Patient Forum Flyer",
          "[Updt By: Grants Load]",
          "Procter & Gamble Co.\tPI\t$9,810\t07/07\t11/11\tEdit\tDelete",
          "CCFA Ref. #1893\tPrevention of Intestinal Fibrosis by Spironolactone in a Rat Model of IBD (Inflammatory Bowel Disease)",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$2,500\t06/07\t08/07\tEdit\tDelete",
          "Clinical Study Agmt. Protocol 512-04-208\tA Prospective, Open Label Study to Evaluate the Adacolumn Apheresis System for the Treatment of Moderate to Severe Crohn's Disease Protocol 512-04-208",
          "[Updt By: Grants Load]",
          "Otsuka America Pharmaceutical, through a consortium with Robarts Clinical Trials - Roba\tPI\t$207,280\t08/06\t12/08\tEdit\tDelete",
          "CCFA Ref. # 1644\tMicrobiota and Inflammatory Bowel Disease",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tPI\t$2,500\t06/06\t09/06\tEdit\tDelete",
          "Clinical Study Agmt. Protocol 512-04-206\tA Randomized, Prospective, Double-Blinded Placebo-Controlled (Sham-Controlled) Study to Evaluate the Safety and Effectiveness of the Adacolumn Apheresis System for the Treatment of Moderate to Severe Crohn's Disease, Protocol 512-04-206",
          "[Updt By: Grants Load]",
          "Otsuka America Pharmaceutical, through a consortium with Robarts Clinical Trials - Roba\tPI\t$207,280\t03/06\t12/08\tEdit\tDelete",
          "Award letter dated 11/16/07\tA Novel, Valid Disease Activity Index for Clinical Research in Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Crohn's and Colitis Foundation\tCo-I with Effort\t$411,155\t01/06\t06/09\tEdit\tDelete",
          "Revised Agreement protocol\tA Randomized, Prospective, Double-Blinded, Placebo-Controlled (Sham-Controlled) Study to Evaluate the Safety and Effectiveness of the Adacolumn Apheresis System for the Treatment of Moderate to Severe Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "Otsuka America Pharmaceutical, through a consortium with Robarts Clinical Trials - Roba\tPI\t$47,796\t01/05\t12/08\tEdit\tDelete",
          "Award letter dated 01/07/04\tDetection of Enteric Fibrosis in Crohn's Disease",
          "[Updt By: Grants Load]",
          "FDHN\tNon-Faculty PI\t$70,000\t07/04\t06/06\tEdit\tDelete",
          "A PHASE III, RANDOMIZED, DOUBLE-BLIND, PLACEBO-CONTROLLED, MULTICENTER STUDY TO EVALUATE THE EFFICACY AND SAFETY OF ETROLIZUMAB AS AN INDUCTION AND MAINTENANCE TREATMENT FOR PATIENTS WITH MODERATELY TO SEVERELY ACTIVE CROHN’S DISEASE",
          "[Updt By: Grants Load]",
          "Genentech, Inc. through a consortium with Quintiles, Inc\tPI\t$0\t\t12/20\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Upadacitinib (ABT-494) in Subjects with Moderately to Severely Active Crohn's Disease Who Have Inadequately Responded to or are Intolerant to Biologic Therapy",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$0\t\t11/20\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Induction Study of the Efficacy and Safety of Upadacitinib (ABT-494) in Subjects with Moderately to Severely Active Crohn's Disease Who Have Inadequately Responded to or are Intolerant to Conventional Therapies but Have Not Failed Biologic Therapy.",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$0\t\t11/20\tEdit\tDelete",
          "A Multicenter, Randomized, Double-Blind, Placebo-Controlled Study to Evaluate the Safety and Efficacy of ABT-494 for Induction and Maintenance Therapy in Subjects with Moderately to Severely Active Ulcerative Colitis",
          "[Updt By: Grants Load]",
          "AbbVie, Inc.\tPI\t$0\t\t01/20\tEdit\tDelete",
          "IBD School Videos",
          "[Updt By: Grants Load]",
          "Takeda Pharmaceuticals USA\tPI\t$0\t\t01/19\tEdit\tDelete")

  
  
  
  
past %>% 
  str_replace_all(pattern = "\tEdit\tDelete", "") %>% 
  read_tsv() %>% 
  janitor::clean_names() %>% 
  filter(grant_number != "[Updt By: phiggins]") %>% 
  filter(grant_number != "[Updt By: Grants Load]") %>%   
  filter(grant_number != "[Updt By: debratan]") %>%   
  mutate(sponsor_name = case_when(is.na(sponsor_name) ~ lead(grant_number), TRUE ~ sponsor_name)) %>% 
  mutate(role_in_grant = case_when(is.na(role_in_grant) ~ lead(title), TRUE ~ role_in_grant)) %>% 
  mutate(total_direct_indirect = case_when(is.na(total_direct_indirect) ~ lead(sponsor_name), TRUE ~ total_direct_indirect)) %>% 
  mutate(begin_dt = case_when(is.na(begin_dt) & str_detect(string = total_direct_indirect, pattern = "$") ~ lead(role_in_grant), TRUE ~ begin_dt)) %>% 
  mutate(end_dt = case_when(is.na(end_dt) & str_detect(total_direct_indirect, "$") ~ lead(total_direct_indirect), TRUE ~ end_dt)) %>% 
  mutate(title = case_when(is.na(title) ~ grant_number, TRUE ~ title)) %>% 
  mutate(grant_number = case_when(title == grant_number ~ "", TRUE ~ grant_number)) %>% 
  filter(str_detect(end_dt, "/")) ->
past_grants

